---
services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    volumes:
      - ../../ccloud/fm-debezium-sqlserver-v2-source/ssl/mssql.conf:/var/opt/mssql/mssql.conf
      - ../../ccloud/fm-debezium-sqlserver-v2-source/ssl/mssql.pem:/tmp/mssql.pem
      - ../../ccloud/fm-debezium-sqlserver-v2-source/ssl/mssql.key:/tmp/mssql.key
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Standard"
      SA_PASSWORD: "Password!"


  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - sqlserver
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-debezium-sqlserver-v2-source/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN