---
version: '3.5'
services:

  nginx_proxy:
    #image: reiz/nginx_proxy:0.0.3
    build:
      context: ../../connect/connect-servicenow-sink/repro-70453/
    hostname: nginx_proxy
    container_name: nginx_proxy
    cap_add:
      - NET_ADMIN
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-servicenow-sink/repro-70453/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    volumes:
      - ../../connect/connect-servicenow-sink/repro-70453/logging.properties:/tmp/logging.properties
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-servicenow
      # KAFKA_OPTS: -Djava.util.logging.config.file=/tmp/logging.properties