tasks:
  - init: |
      curl -L --http1.1 https://cnfl.io/ccloud-cli | sudo sh -s -- -b /usr/local/bin
      cd environment/plaintext && ./start.sh; ./stop.sh
ports:
  - port: 9021
    onOpen: open-browser

vscode:
  extensions:
    - ms-azuretools.vscode-docker