---
version: '3.5'
services:

  # this ldap instance is not used by RBAC, it is only used to perform ldapsearch
  openldap:
      volumes:
        - ../../environment/rbac-sasl-plain/scripts/security/ldap_users:/container/service/slapd/assets/config/bootstrap/ldif/custom
        - ../../other/rbac-with-azure-ad/cert.cer:/tmp/cert.txt

  broker:
    volumes:
      - ../../environment/rbac-sasl-plain/kafka/kafka.jaas.conf:/etc/kafka/kafka_server_jaas.conf
      - ../../environment/rbac-sasl-plain/conf:/tmp/conf
      - ../../environment/rbac-sasl-plain/scripts/helper:/tmp/helper
      - ../../other/rbac-with-azure-ad/truststore.jks:/tmp/truststore.jks
    environment:
      KAFKA_LOG4J_LOGGERS: "io.confluent.rest-utils=DEBUG,io.confluent.rbacapi=DEBUG,io.confluent.tokenapi=DEBUG,io.confluent.security.auth=DEBUG,io.confluent.security.store=DEBUG,io.confluent.common.security.jetty=DEBUG"
      CONFLUENT_METRICS_REPORTER_SASL_JAAS_CONFIG: "org.apache.kafka.common.security.plain.PlainLoginModule required \
          username=\"admin\" \
          password=\"Sugt5676\";"
      KAFKA_LISTENER_NAME_INTERNAL_PLAIN_SASL_JAAS_CONFIG: |
              org.apache.kafka.common.security.plain.PlainLoginModule required \
              username="admin" \
              password="Sugt5676" \
              user_admin="Sugt5676" \
              user_mds="Zagu8964";

      # Configure MDS to talk to AD/LDAP
      KAFKA_LDAP_JAVA_NAMING_FACTORY_INITIAL: com.sun.jndi.ldap.LdapCtxFactory
      KAFKA_LDAP_COM_SUN_JNDI_LDAP_READ_TIMEOUT: 3000
      KAFKA_LDAP_JAVA_NAMING_PROVIDER_URL: ldaps://ldaps.mydomain.onmicrosoft.com:636
      # Authenticate to LDAP
      KAFKA_LDAP_JAVA_NAMING_SECURITY_PRINCIPAL: CN=admin,OU=AADDC Users,DC=mydomain,DC=onmicrosoft,DC=com
      KAFKA_LDAP_JAVA_NAMING_SECURITY_CREDENTIALS: Sugt5676
      KAFKA_LDAP_JAVA_NAMING_SECURITY_AUTHENTICATION: simple
      KAFKA_LDAP_JAVA_NAMING_SECURITY_PROTOCOL: SSL
      KAFKA_LDAP_SSL_TRUSTSTORE_LOCATION: /tmp/truststore.jks
      KAFKA_LDAP_SSL_TRUSTSTORE_PASSWORD: confluent

      # Locate LDAP users and groups
      # KAFKA_LDAP_SEARCH_MODE: GROUPS
      # KAFKA_LDAP_GROUP_SEARCH_BASE: ou=groups,dc=confluentdemo,dc=io
      # KAFKA_LDAP_GROUP_NAME_ATTRIBUTE: cn
      # KAFKA_LDAP_GROUP_MEMBER_ATTRIBUTE: memberOf
      # KAFKA_LDAP_GROUP_OBJECT_CLASS: posixGroup
      # KAFKA_LDAP_GROUP_MEMBER_ATTRIBUTE_PATTERN: cn=(.*),ou=users,dc=confluentdemo,dc=io
      # KAFKA_LDAP_USER_SEARCH_BASE: OU=AADDC Users,DC=mydomain,DC=onmicrosoft,DC=com
      # KAFKA_LDAP_USER_NAME_ATTRIBUTE: cn
      # KAFKA_LDAP_USER_OBJECT_CLASS: user

      # How to locate users and groups
      KAFKA_LDAP_SEARCH_MODE: USERS
      KAFKA_LDAP_USER_SEARCH_BASE: OU=AADDC Users,DC=mydomain,DC=onmicrosoft,DC=com
      KAFKA_LDAP_USER_NAME_ATTRIBUTE: cn
      KAFKA_LDAP_USER_OBJECT_CLASS: user
      KAFKA_LDAP_USER_MEMBEROF_ATTRIBUTE: memberOf
      KAFKA_LDAP_USER_MEMBEROF_ATTRIBUTE_PATTERN: "CN=(.*),OU=AADDC Users,.*"
      # https://docs.confluent.io/5.5.0/security/ldap-authorizer/configuration.html#configuring-ssl-for-ldap
      KAFKA_OPTS: -Djava.security.auth.login.config=/etc/kafka/kafka_server_jaas.conf
                  -Dcom.sun.jndi.ldap.object.disableEndpointIdentification=true
                  -Djavax.net.debug=all

  schema-registry:
      environment:
          SCHEMA_REGISTRY_KAFKASTORE_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="schemaregistryUser" \
                  password="Tapu2399" \
                  metadataServerUrls="http://broker:8091";

  connect:
      environment:
          CONNECT_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";
          CONNECT_PRODUCER_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";
          CONNECT_PRODUCER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";
          CONNECT_CONSUMER_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";
          CONNECT_CONSUMER_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";
          CONNECT_ADMIN_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="connectAdmin" \
                  password="UTu178cdd8" \
                  metadataServerUrls="http://broker:8091";

  ksqldb-server:
    environment:
        KSQL_SASL_JAAS_CONFIG: |
                org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                username="ksqlDBAdmin" \
                password="Yoco7654" \
                metadataServerUrls="http://broker:8091";
        KSQL_CONFLUENT_MONITORING_INTERCEPTOR_SASL_JAAS_CONFIG: |
                org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                username="ksqlDBAdmin" \
                password="Yoco7654" \
                metadataServerUrls="http://broker:8091";

  control-center:
      environment:
          CONTROL_CENTER_STREAMS_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="controlcenterAdmin" \
                  password="Badu1234" \
                  metadataServerUrls="http://broker:8091";
          CONTROL_CENTER_KAFKA_MYCLUSTER_SASL_JAAS_CONFIG: |
                  org.apache.kafka.common.security.oauthbearer.OAuthBearerLoginModule required \
                  username="controlcenterAdmin" \
                  password="Badu1234" \
                  metadataServerUrls="http://broker:8091";