---
version: '3.5'
services:
  activemq:
    image: rmohr/activemq:5.15.9
    hostname: activemq
    container_name: activemq
    volumes:
        - ../../connect/connect-active-mq-source/security/kafka.activemq.truststore.jks:/tmp/kafka.activemq.truststore.jks
        - ../../connect/connect-active-mq-source/security/kafka.activemq.keystore.jks:/tmp/kafka.activemq.keystore.jks
        - ../../connect/connect-active-mq-source/activemq.xml:/opt/apache-activemq-5.15.9/conf/activemq.xml

  connect:
    volumes:
        - ../../connect/connect-active-mq-source/security/kafka.connect.truststore.jks:/tmp/truststore.jks
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-activemq
      KAFKA_OPTS:  -Djavax.net.debug=all
                  -Djavax.net.ssl.trustStore=/tmp/truststore.jks
                  -Djavax.net.ssl.trustStorePassword=confluent