---
version: '3.5'

services:
  # https://github.com/Knappek/docker-hadoop-secure
  kdc:
    image: sequenceiq/kerberos
    hostname: kdc.kerberos-demo.local
    container_name: kdc
    environment:
      REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos-demo.local
    volumes:
      - ../../connect/connect-hdfs2-source/kerberos/krb5.conf:/etc/krb5.conf
      - /dev/urandom:/dev/random
      - /etc/localtime:/etc/localtime:ro

  # https://github.com/Knappek/docker-hadoop-secure
  hadoop:
    image: knappek/hadoop-secure:2.7.4
    depends_on:
      - kdc
    hostname: hadoop.kerberos-demo.local
    container_name: hadoop
    environment:
      KRB_REALM: EXAMPLE.COM
      DOMAIN_REALM: kdc.kerberos-demo.local
      FQDN: hadoop.kerberos-demo.local
      KERBEROS_ROOT_USER_PASSWORD: password
    volumes:
      - ../../connect/connect-hdfs2-source/kerberos/krb5.conf:/etc/krb5.conf
      - /etc/localtime:/etc/localtime:ro

  connect:
    hostname: connect.kerberos-demo.local
    volumes:
      - ../../connect/connect-hdfs2-source/kerberos/krb5.conf:/etc/krb5.conf
      - ../../connect/connect-hdfs2-source/kerberos/core-site.xml:/etc/hadoop/core-site.xml
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hdfs2-source,/usr/share/confluent-hub-components/confluentinc-kafka-connect-hdfs

networks:
  default:
    name: kerberos-demo.local