---
version: '3.5'
services:

  nginx_proxy:
    image: reiz/nginx_proxy:0.0.3
    hostname: nginx_proxy
    container_name: nginx_proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-servicenow-source/repro-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-servicenow