---
version: '3.5'
services:

  producer-acl:
    build:
      context: ../kafka-admin/producer-acl/
      args:
        TAG: ${TAG}
        CP_BASE_IMAGE: ${CP_BASE_IMAGE}
    hostname: producer-acl
    container_name: producer-acl
