---
services:

  rabbitmq:
    image: rabbitmq:3.8.19-alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "8080:8080"
    environment:
      RABBITMQ_DEFAULT_USER: "myuser"
      RABBITMQ_DEFAULT_PASS: "mypassword"

  rabbitmq_producer:
    build:
      context: ../../ccloud/fm-rabbitmq-source/producer
    hostname: rabbitmq_producer
    container_name: rabbitmq_producer

  rabbitmq_consumer:
    build:
      context: ../../ccloud/fm-rabbitmq-source/consumer
    hostname: rabbitmq_consumer
    container_name: rabbitmq_consumer

  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - rabbitmq
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-rabbitmq-source/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN