---
version: '3.5'
services:
  connect:
    volumes:
        - ../../connect/connect-filestream-sink/data:$CONNECT_CONTAINER_HOME_DIR/data
        - ../../ksqldb/benchmarking-scenarios/schemas:/tmp/schemas
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-datagen