---
services:
  mysql:
    image: mysql:8.1
    hostname: mysql
    container_name: mysql
    volumes:
      - ../../connect/connect-jdbc-mysql-sink/mysql-init.sql:/docker-entrypoint-initdb.d/mysql-init.sql
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: 172.%  # Allow docker containers to connect to mysql

  connect:
    depends_on:
      - mysql
    volumes:
        - ../../connect/connect-jdbc-mysql-sink/mysql-connector-j-8.4.0.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc/lib/mysql-connector-j-8.4.0.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jdbc