---
version: '3.5'
services:

  splunk:
    image: splunk/splunk:9.2.0.1
    hostname: splunk
    container_name: splunk
    platform: linux/amd64
    ports:
      - 8000:8000
    volumes:
      - ../../ccloud/fm-splunk-sink/default.yml:/tmp/defaults/default.yml
    environment:
      SPLUNK_START_ARGS: --accept-license
      SPLUNK_USERNAME: admin
      SPLUNK_PASSWORD: password
      DEBUG: "true"


  # https://ngrok.com/docs/using-ngrok-with/docker/
  ngrok:
    image: ngrok/ngrok:latest
    hostname: ngrok
    container_name: ngrok
    ports:
      - 4040:4040
    restart: unless-stopped
    links:
      - splunk
    command:
      - "start"
      - "--all"
      - "--log=stdout"
      - "--config"
      - "/etc/ngrok.yml"
    volumes:
      - ../../ccloud/fm-splunk-sink/ngrok.yml:/etc/ngrok.yml
    environment:
      NGROK_AUTHTOKEN: $NGROK_AUTH_TOKEN