---
version: '3.5'
services:
  weblogic-jms:
    image: weblogic-jms:latest
    hostname: weblogic-jms
    container_name: weblogic-jms
    ports:
      - '7001:7001'

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - weblogic-jms
    volumes:
        - ../../connect/connect-jms-weblogic-sink/wlthint3client.jar:/usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink/lib/wlthint3client.jar
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-jms-sink
      # CONNECT_LOG4J_ROOT_LOGLEVEL: TRACE
