---
version: '3.5'
services:

  sfdx-cli:
    image: vdesabou/sfdx-cli:latest # forked from salestrip/sfdx-cli to add plugin sfpowerkit
    hostname: sfdx-cli
    container_name: sfdx-cli
    command: "sleep infinity"
    volumes:
    - ../../ccloud/fm-salesforce-pushtopics-source/MyLeadPushTopics.apex:/tmp/MyLeadPushTopics.apex