---
version: '3.5'
services:

  connect:
    volumes:
      - ../../connect/connect-http-sink/security:/tmp
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/castorm-kafka-connect-http
      KAFKA_OPTS: -Djavax.net.ssl.trustStore=/tmp/truststore.http-service-mtls-auth.jks
                  -Djavax.net.ssl.trustStorePassword=confluent
                 # -Djavax.net.ssl.trustStoreType=pkcs12

  http-service-mtls-auth:
    image: vdesabou/http-sink-demo
    hostname: http-service-mtls-auth
    container_name: http-service-mtls-auth
    ports:
      - "8643:8443"
    environment:
      SPRING_PROFILES_ACTIVE: 'ssl-auth'
      