---
services:
  connect:
    volumes:
      - ../../connect/connect-azure-cosmosdb-source/data:/data
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/microsoftcorporation-kafka-connect-cosmos

  # https://pypi.org/project/azure-cosmos/
  azure-cosmos-client:
    build:
      context: ../../connect/connect-azure-cosmosdb-source/azure-cosmos-client
    hostname: azure-cosmos-client
    container_name: azure-cosmos-client