---
version: '3.5'

services:

  krb5:
    image: flokkr/krb5
    hostname: krb5.kerberos-demo.local
    container_name: krb5
    volumes:
    - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  namenode1:
    image: flokkr/hadoop:latest
    hostname: namenode1.kerberos-demo.local
    container_name: namenode1
    depends_on:
      - krb5
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    environment:
        ENSURE_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
        SLEEP_SECONDS: 20
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    command: ["hdfs", "namenode"]
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf
  namenode2:
    image: flokkr/hadoop:latest
    hostname: namenode2.kerberos-demo.local
    container_name: namenode2
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    depends_on:
      - krb5
    environment:
        ENSURE_STANDBY_NAMENODE_DIR: "/tmp/hadoop-hadoop/dfs/name"
        #ENSURE_NAMENODE_CLUSTERID: "sh"
        SLEEP_SECONDS: 40
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    command: ["hdfs", "namenode"]
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  journal1:
    image: flokkr/hadoop:latest
    hostname: journal1.kerberos-demo.local
    container_name: journal1
    depends_on:
      - krb5
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    #environment:
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    command: ["hdfs", "journalnode"]
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  journal2:
    image: flokkr/hadoop:latest
    hostname: journal2.kerberos-demo.local
    container_name: journal2
    depends_on:
      - krb5
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    #environment:
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    command: ["hdfs", "journalnode"]
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  journal3:
    image: flokkr/hadoop:latest
    hostname: journal3.kerberos-demo.local
    container_name: journal3
    depends_on:
      - krb5
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    command: ["hdfs", "journalnode"]
    #environment:
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  datanode:
    image: flokkr/hadoop:latest
    command: ["hdfs", "datanode"]
    hostname: datanode.kerberos-demo.local
    container_name: datanode
    depends_on:
      - krb5
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    environment:
        SLEEP_SECONDS: 50
        # HADOOP_OPTS: "-Djava.net.preferIPv4Stack=true -Dsun.security.krb5.debug=true -Dsun.security.spnego.debug"
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  resourcemanager:
    image: flokkr/hadoop:latest
    hostname: resourcemanager.kerberos-demo.local
    container_name: resourcemanager
    depends_on:
      - krb5
    command: ["yarn", "resourcemanager"]
    ports:
        - 8088:8088
    env_file:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    volumes:
        - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/opt/launcher/plugins/011_kerberos/krb5.conf

  activator:
    image: flokkr/hadoop:latest
    hostname: activator.kerberos-demo.local
    container_name: activator
    depends_on:
      - krb5
    command: ["hdfs", "haadmin", "-transitionToActive", "nn1"]
    env_file:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/config
    environment:
        SLEEP_SECONDS: 60

  connect:
    hostname: connect.kerberos-demo.local
    volumes:
      - ../../connect/connect-hdfs3-sink/ha-kerberos/krb5.conf:/etc/krb5.conf
      #- ../../connect/connect-hdfs3-sink/kerberos/core-site.xml:/etc/hadoop/core-site.xml
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hdfs3

networks:
  default:
    name: kerberos-demo.local