---
version: '3.5'
services:

  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    ports:
      - "8888:8888"
    volumes:
      - ../../connect/connect-hbase-sink/repro-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  hbase:
    image: daunnc/hbase:2.2.4 # https://github.com/pomadchin/hbase-docker
    hostname: hbase
    container_name: hbase

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - hbase
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/confluentinc-kafka-connect-hbase
    # dns: 0.0.0.0