---
version: '3.5'
services:
  sqlserver:
    image: mcr.microsoft.com/azure-sql-edge
    hostname: sqlserver
    container_name: sqlserver
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: "1"
      MSSQL_AGENT_ENABLED: "true"
      MSSQL_PID: "Developer"
      MSSQL_SA_PASSWORD: "Password!"

  connect:
    depends_on:
      - zookeeper
      - broker
      - schema-registry
      - sqlserver
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/debezium-debezium-connector-sqlserver