---
version: '3.5'
services:

  nginx-proxy:
    image: reiz/nginx_proxy:latest
    hostname: nginx-proxy
    container_name: nginx-proxy
    depends_on:
    - schema-registry
    ports:
      - "8888:8888"
    volumes:
      - ../../other/http-proxy-schema-registry/nginx-proxy/nginx_whitelist.conf:/usr/local/nginx/conf/nginx.conf

  connect:
    environment:
      # in newer version, it is located in /usr/share/filestream-connectors
      CONNECT_PLUGIN_PATH: /usr/share/java/,/usr/share/confluent-hub-components/,/usr/share/filestream-connectors