---
services:
  redis:
    image: redis:7.2.4
    hostname: redis
    container_name: redis

  connect:
    depends_on:
      - redis
    environment:
      CONNECT_PLUGIN_PATH: /usr/share/confluent-hub-components/jcustenborder-kafka-connect-redis